USE master;  
GO  
ALTER DATABASE [DataBaseNameOld] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE [DataBaseNameOld] MODIFY NAME = [DataBaseNamenew];
GO  
ALTER DATABASE [DataBaseNamenew] SET MULTI_USER;
GO